# Site settings
language:               ""
title:                  "Ascent"
description:            "Collaborative Consulting"
google-verification:    ""

# Handling Reading
include:
  - ".htaccess"
  - "_pages"

exclude:
  - "/assets/"
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"

# Plugins
gems:             ["jekyll-sitemap", "jekyll-paginate"]

# Conversion
incremental:      true

# Serving
url:            ""
baseurl:        "" # does not include hostname

# Outputting
permalink:        "/blog/:year/:title/"
paginate_path:    "/blog/page:num"
paginate:         5

compress_html:
  ignore:
    envs: [development]

# Jekyll Collections
collections:
  pages:
    title: pages
    output: true
    permalink: /:path/
  sections:
    title: sections
    output: false
    permalink: /sections/:path/

defaults:
  - scope:
      path: "/pages/"
      type: pages
    values:
      layout: page
  - scope:
      path: "/sections/"
      type: sections
    values:
      layout: page
